version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "80:80"
  frontend:
    build: ./client
    ports:
      - "3000:3000"
  server:
    build: ./server
    ports:
      - "3001:3001"
