version: "3.8"
services:
  api:
    build:
      context: ./api  
    ports:
      - "80:80"
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
